[target.armv5te-unknown-linux-gnueabi]
linker="/home/alexey/Dev/lab/pbook/gdrive/ldwrap.sh"
rustflags = [
    "-C", "link-arg=-march=armv5te",
    "-C", "link-arg=-mfpu=vfp",
    "-C", "link-arg=-mfloat-abi=softfp",
    "-C", "link-arg=-static-libgcc",
    "-C", "link-arg=-fno-exceptions",
    "-C", "link-arg=--sysroot=/home/alexey/Dev/lab/pbook/FRSCSDK/arm-none-linux-gnueabi/sysroot",
]
